### ISSUE TITLE
1 errors encountered while parsing '"ass"' subtitle using the "Advanced Sub Station Alpha" format parser

### ISSUE THREAD

**Issue by dandud100** [jellyfin/jellyfin-plugin-subtitleextract#30] opened 2024-06-09 11:43 UTC
Uhm, did the conversation work or not? I am not sure because of this error message.

```
[2024-06-09 13:13:25.803 +02:00] [INF] [28] Emby.Server.Implementations.IO.LibraryMonitor: "movies" ("/data/movies") will be refreshed.
[2024-06-09 13:13:25.958 +02:00] [INF] [55] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "Robots", Path: "/data/movies/Robots (2005) [imdbid-tt0358082]/Robots (2005) [imdbid-tt0358082] - [Bluray-1080p][AC3 5.1][x265]-FuN.mkv", Id: 86de1b35-1dea-1cda-0377-f3c5f5707cd1
[2024-06-09 13:13:26.194 +02:00] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies/Robots (2005) [imdbid-tt0358082]/Robots (2005) [imdbid-tt0358082] - [Bluray-1080p][DTS 5.1][x264]--.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-06-09 13:13:39.667 +02:00] [INF] [19] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.253.0.2" request
[2024-06-09 13:14:23.436 +02:00] [INF] [74] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i \"/data/movies/Robots (2005) [imdbid-tt0358082]/Robots (2005) [imdbid-tt0358082] - [Bluray-1080p][DTS 5.1][x264]--.mkv\" -copyts -map 0:3 -an -vn -c:s copy \"/config/data/data/subtitles/2/29731ce4-36ce-e9d1-321b-42f0161b6c70.srt\""
[2024-06-09 13:14:57.418 +02:00] [INF] [19] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "/data/movies/Robots (2005) [imdbid-tt0358082]/Robots (2005) [imdbid-tt0358082] - [Bluray-1080p][DTS 5.1][x264]--.mkv" to "/config/data/data/subtitles/2/29731ce4-36ce-e9d1-321b-42f0161b6c70.srt"
[2024-06-09 13:14:57.984 +02:00] [ERR] [19] MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: 1 errors encountered while parsing '"ass"' subtitle using the "Advanced Sub Station Alpha" format parser
[2024-06-09 13:14:59.274 +02:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Subtitle Extract" Completed after 0 minute(s) and 35 seconds
```

**Comment by solidsnake1298** [comment] 2024-06-30 02:05
I can confirm that I have the same behavior with Subtitle Extract and ASS subs.

**Comment by dandud100** [comment] 2024-06-30 07:15
Thank you, I think it worked to a certain point. For me it could be broken for two reasons:

1. I switched my Server from AMD to Intel N100
2. Some Jellyfin update

**Comment by Jellyboi420** [comment] 2024-07-18 06:39
For me it worked on a native Ubuntu desktop installation but since I moved over to an LXC on Proxmox I have the same behaviour. Maybe certain forms of installation lack a certain prerequisit for this?

**Comment by crobibero** [comment] 2024-07-24 13:40
This isn't an issue with the plugin but the upstream library.
Fixed by https://github.com/jellyfin/jellyfin/pull/12329

**Closed by crobibero** 2024-07-24 13:40 UTC
Labels: confirmed
